<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>UnitTests</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit.v3" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Data\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Enigma.LicenseManager\Enigma.LicenseManager.csproj" />
      <ProjectReference Include="..\Enigma.LicenseManager.Tools\Enigma.LicenseManager.Tools.csproj" />
      <ProjectReference Include="..\Enigma.LicenseManager.Cli\Enigma.LicenseManager.Cli.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Data\MLDSA1_private.pem">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Data\MLDSA1_public.pem">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Data\MLDSA2_private.pem">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Data\MLDSA2_public.pem">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Data\RSA1_private.pem">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Data\RSA1_public.pem">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Data\RSA2_private.pem">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Data\RSA2_public.pem">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
